### ISSUE TITLE
Filters are rendered in arbitrary order

### ISSUE THREAD

**Issue by rxbn** [projectsyn/component-fluentbit#5]
Fluent-bit filters are executed in the order that they appear in the config file. Currently the component renders the entries present in `parameters.fluentbit.filters` in an arbitrary order, leading to unintentional behavior, especially with filters like `grep`.

## Steps to Reproduce the Problem

  1. Configure a set of filters that depend on each other
  1. Render the config
  1. Note that filters appear in an arbitrary order

## Actual Behavior

Filter configured in parameters are rendered in an arbitrary order.

## Expected Behavior

Filters configured in parameters are rendered in a well-defined order

**Comment by simu** [comment]
Potential solution: introduce a field which specifies sort order of filters.
